# Retrieving Data From Edgar

In this notebook, I will explore pulling the necessary data from EDGAR--a public database containing all the quarterly and annual financial reports required by law. First, I will take a look at one company, American Airlines (AAL), and then extrapolate the code to include all necessary companies. 

We will be using the sec_edgar_downloader package for this, as it is an extremely powerful and simple tool to scrape the necessary data. More information about the package can be found here:

https://pypi.org/project/sec-edgar-downloader/

In [2]:
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import os
import re
import html2text
import pickle
from sec_edgar_downloader import Downloader

## American Airlines Sample

First, we will start with the 10K filing. I provided my opinion on the valuable parts in the 10K analysis file found in the github.

In [3]:
company = 'American Airlines Inc'
ticker = 'AAL'

# Initialize a downloader instance. If no argument is passed
# to the constructor, the package will download filings to
# the current working directory.
dl = Downloader()

In [4]:
# Get all 10-K filings for American Airlines (ticker: AAL) from 2000 onwards
dl.get("10-K", ticker, after="2000-01-01")

19

The above request downloads the specified reports into the working directory:

In [5]:
pulls = os.listdir("sec-edgar-filings/AAL/10-K")
pulls[:10]

['0000004515-08-000014',
 '0000006201-20-000023',
 '0000950134-06-003715',
 '0001047469-03-013301',
 '0000950134-05-003726',
 '0000950134-04-002668',
 '0000006201-10-000006',
 '0000950123-11-014726',
 '0000006201-18-000009',
 '0001193125-15-061145']

In [6]:
# We want the one from 2021
os.listdir("sec-edgar-filings/AAL/10-K/0001193125-15-061145")

['full-submission.txt', 'filing-details.html']

We can see here that there are two files. Let us explore these files:

In [7]:
# Get the most recent filing
f = open("sec-edgar-filings/AAL/10-K/0001193125-15-061145/filing-details.html", "r")
raw_10k = f.read()

In [8]:
print(raw_10k[:500])

<html><body><document>
<type>10-K
<sequence>1
<filename>d829913d10k.htm
<description>FORM 10-K
<text>
<title>Form 10-K</title>
<h5 align="left"><a href="#toc">Table of Contents</a></h5>
<p style="line-height:4px;margin-top:0px;margin-bottom:0px;border-bottom:2pt solid #000000">&#160;</p>
<p style="line-height:3px;margin-top:0px;margin-bottom:2px;border-bottom:0.5pt solid #000000">&#160;</p> <p align="center" style="margin-top:1px;margin-bottom:0px"><font size="2" style="font-family:Times New Rom

In [9]:
soup = BeautifulSoup(raw_10k, 'lxml')

Since the SEC requires the documents to follow a certain format, containing items labelled similarly, we should be able to parse the documents easily once one is taken care of. Let us begin to explore the HTML file:

In [10]:
document = soup.html.find_all()

el = ['html',]  # we already include the html tag
for n in document:
    if n.name not in el:
        el.append(n.name)

print(el)

['html', 'body', 'document', 'type', 'sequence', 'filename', 'description', 'text', 'title', 'h5', 'a', 'p', 'font', 'b', 'center', 'table', 'tr', 'td', 'i', 'hr', 'sup', 'br', 'img', 'u']

In [12]:
goods = soup.find_all('b')
[x.text for x in goods[106:110]]

['ITEM\xa01A.\xa0\xa0RISK FACTORS ',
 'Risk Factors Relating to the Company and Industry-Related Risks ',
 'We could experience significant operating losses in the future. ',
 'Downturns in economic conditions adversely affect our business. ']

In [13]:
goods

[<b>UNITED STATES SECURITIES AND
 EXCHANGE COMMISSION </b>,
 <b>Washington, D.C. 20549 </b>,
 <b>FORM 10-K </b>,
 <b></b>,
 <b></b>,
 <b></b>,
 <b>ANNUAL REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934 </b>,
 <b>For the Fiscal Year Ended December 31, 2014 </b>,
 <b></b>,
 <b></b>,
 <b></b>,
 <b>TRANSITION REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934 </b>,
 <b>For the Transition Period
 From                     to
 </b>,
 <b>American
 Airlines Group Inc. </b>,
 <b>Delaware</b>,
 <b>75-1825172</b>,
 <b>4333 Amon Carter Blvd., Fort Worth, Texas 76155</b>,
 <b>(817) 963-1234</b>,
 <b>Securities registered pursuant to Section 12(b) of the Act:
 </b>,
 <b>Name of Exchange on Which Registered</b>,
 <b>Securities registered pursuant to Section 12(g) of the Act: None </b>,
 <b>American Airlines, Inc. </b>,
 <b>Delaware</b>,
 <b>13-1502798</b>,
 <b>4333 Amon Carter Blvd., Fort Worth, Texas 76155</b>,
 <b>(817) 963-1234</b>,
 <b>Securities registered pursuant to Section 12(b) of the Act: None </b>,
 <b>Securities registered pursuant to Section 12(g) of the Act: None </b>,
 <b>DOCUMENTS INCORPORATED BY REFERENCE </b>,
 <b>American Airlines Group Inc. </b>,
 <b>American Airlines, Inc. </b>,
 <b>Form 10-K </b>,
 <b>Year Ended December 31, 2014 </b>,
 <b><a name="toc"></a>Table of Contents </b>,
 <b>Page</b>,
 <b><a href="#tx829913_1">PART I </a></b>,
 <b><a href="#tx829913_1"></a>  </b>,
 <b><a href="#tx829913_8">PART II </a></b>,
 <b><a href="#tx829913_8"></a>  </b>,
 <b><a href="#tx829913_17">PART III </a></b>,
 <b><a href="#tx829913_17"></a>  </b>,
 <b><a href="#tx829913_23">PART IV </a></b>,
 <b><a href="#tx829913_23"></a>  </b>,
 <b>Glossary of Terms </b>,
 <b>Note Concerning Forward-Looking Statements </b>,
 <b><a name="tx829913_1"></a>PART I </b>,
 <b><a name="tx829913_2"></a>ITEM 1.  BUSINESS</b>,
 <b></b>,
 <b>Overview </b>,
 <b>Chapter 11 Reorganization </b>,
 <b>Merger </b>,
 <b>Airline Operations </b>,
 <b>one</b>,
 <b>Regional Operations </b>,
 <b>Cargo </b>,
 <b>Other Revenues </b>,
 <b>The U.S. Airline Industry </b>,
 <b>Competition
 </b>,
 <b>Marketing and Alliance Agreements with Other Airlines </b>,
 <b>one</b>,
 <b>one</b>,
 <b>one</b>,
 <b>one</b>,
 <b>one</b>,
 <b>Industry Regulation and Airport Access
 </b>,
 <b><i>General </i></b>,
 <b><i>International </i></b>,
 <b><i>Security </i></b>,
 <b><i>Airline Fares </i></b>,
 <b><i>Airport Access and Operations </i></b>,
 <b><i>Civil Reserve Air Fleet </i></b>,
 <b><i>Environmental Matters </i></b>,
 <b><i>Future Regulatory Developments </i></b>,
 <b>Employees and Labor Relations </b>,
 <b>American</b>,
 <b>US Airways</b>,
 <b>Wholly-owned<br/>Regional Carriers</b>,
 <b>Total</b>,
 <b>Union</b>,
 <b>Class or Craft</b>,
 <b>Employees (1)</b>,
 <b>Contract<br/>Amendable Date (2)</b>,
 <b>New American:</b>,
 <b>American Mainline:</b>,
 <b>US Airways Mainline:</b>,
 <b>Envoy:</b>,
 <b>Piedmont:</b>,
 <b>PSA:</b>,
 <b>Aircraft Fuel </b>,
 <b>Year</b>,
 <b>Gallons</b>,
 <b>Average Price<br/>per Gallon</b>,
 <b>Aircraft Fuel<br/>Expense</b>,
 <b>Percent of Total<br/>Mainline Operating<br/>Expenses</b>,
 <b>Insurance </b>,
 <b>Customer Service </b>,
 <b>December 31,</b>,
 <b>Better</b>,
 <b>(Worse)</b>,
 <b>2014</b>,
 <b>2013 (a)</b>,
 <b>Frequent Flyer Programs </b>,
 <b>Ticket Distribution </b>,
 <b>Seasonality and Other Factors </b>,
 <b>Available Information </b>,
 <b>GLOSSARY OF TERMS </b>,
 <b><a name="tx829913_3"></a>ITEM 1A.  RISK FACTORS </b>,
 <b>Risk Factors Relating to the Company and Industry-Related Risks </b>,
 <b><i>We could experience significant operating losses in the future. </i></b>,
 <b><i>Downturns in economic conditions adversely affect our business. </i></b>,
 <b><i>Our business is dependent on the price and availability of aircraft fuel. Continued periods of high volatility in fuel costs, increased fuel prices and significant disruptions in the supply of
 aircraft fuel could have a significant negative impact on our operating results and liquidity. </i></b>,
 <b><i>The airline industry is intensely competitive and dynamic. </i></b>,
 <b><i>We may be unable to integrate operations successfully and realize the anticipated synergies and other benefits of the
 Merger. </i></b>,
 <b><i>Our
 indebtedness and other obligations are substantial and could adversely affect our business and liquidity. </i></b>,
 <b><i>We will need to obtain sufficient financing or other capital to operate successfully. </i></b>,
 <b><i>Increased costs of financing, a reduction in the
 availability of financing and fluctuations in interest rates could adversely affect our liquidity, results of operations and financial condition. </i></b>,
 <b><i>Our high level of fixed obligations may limit our ability to fund general corporate requirements and obtain additional financing, may limit our flexibility in responding to competitive developments
 and causes our business to be vulnerable to adverse economic and industry conditions. </i></b>,
 <b><i>We have significant pension and other post-employment benefit funding obligations, which may adversely affect our liquidity, results of operations and financial condition. </i></b>,
 <b><i>Any failure to comply with the covenants contained in our financing arrangements may have a material adverse effect on our business, results of operations and financial condition.
 </i></b>,
 <b><i>If our financial
 condition worsens, provisions in our credit card processing and other commercial agreements may adversely affect our liquidity. </i></b>,
 <b><i>The historical consolidated financial information contained in this report is not directly comparable to our financial
 information for prior or future periods</i></b>,
 <b><i> </i></b>,
 <b><i>Union disputes, employee strikes and other labor-related disruptions may adversely affect our operations. </i></b>,
 <b><i>The inability to maintain labor costs at competitive levels would harm our financial performance. </i></b>,
 <b><i>Interruptions or
 disruptions in service at one of our hub airports could have a material adverse impact on our operations. </i></b>,
 <b><i>Ongoing data security compliance requirements could increase our costs, and any
 significant data breach could disrupt our operations and harm our reputation, business, results of operations and financial condition. </i></b>,
 <b><i>If we are unable to obtain and maintain adequate facilities and infrastructure throughout our system and, at
 some airports, adequate Slots, we may be unable to operate our existing flight schedule and to expand or change our route network in the future, which may have a material adverse impact on our operations. </i></b>,
 <b><i>If we incur problems with any of our third-party regional operators or third-party service providers, our operations could be adversely affected by a resulting decline in revenue or negative public
 perception about our services. </i></b>,
 <b><i>We rely on third-party distribution
 channels and must manage effectively the costs, rights and functionality of these channels. </i></b>,
 <b><i>Our business is subject to extensive government regulation, which may result in increases in our costs, disruptions to our operations, limits on our operating flexibility, reductions in the demand
 for air travel, and competitive disadvantages. </i></b>,
 <b><i>The airline industry is heavily
 taxed. </i></b>,
 <b><i>Changes to our business model that are designed to increase revenues may not be
 successful and may cause operational difficulties or decreased demand. </i></b>,
 <b><i>The loss of key personnel upon whom we depend to operate our business or the inability to attract
 additional qualified personnel could adversely affect our business. </i></b>,
 <b><i>We may be adversely affected by conflicts overseas or terrorist attacks; the travel industry continues to face ongoing security concerns. </i></b>,
 <b><i>We operate a global business with international operations that are subject to
 economic and political instability and have been, and in the future may continue to be, adversely affected by numerous events, circumstances or government actions beyond our control. </i></b>,
 <b><i>We are subject to many forms of environmental regulation and may incur substantial costs as a result.
 </i></b>,
 <b><i>We rely heavily on technology and automated systems to operate our business, and any failure of these technologies or systems could harm our business, results of operations and financial condition.
 </i></b>,
 <b><i>We face challenges in
 integrating our computer, communications and other technology systems. </i></b>,
 <b><i>We are at risk of losses and adverse publicity stemming from any accident involving any of our aircraft or the aircraft of our regional or codeshare operators. </i></b>,
 <b><i>Delays in scheduled aircraft deliveries or other loss of anticipated fleet capacity,
 and failure of new aircraft to perform as expected, may adversely impact our business, results of operations and financial condition. </i></b>,
 <b><i>We depend on a limited number of suppliers for aircraft, aircraft
 engines and parts. </i></b>,
 <b><i>Our business has been and will continue to be affected by many changing economic and other conditions beyond our control, including global events that affect travel behavior, and our results of
 operations could be volatile and fluctuate due to seasonality. </i></b>,
 <b><i>A higher than normal number of pilot retirements and a potential shortage of pilots
 could adversely affect us. </i></b>,
 <b><i>Increases in insurance costs or reductions in insurance coverage may adversely impact our operations and financial results.
 </i></b>,
 <b><i>A lawsuit filed in connection with the Merger remains pending, and this lawsuit could have a material adverse impact on our business. </i></b>,
 <b><i>Our ability to utilize our NOL Carryforwards may be limited. </i></b>,
 <b><i>The application of the acquisition method of accounting resulted in AAG recording a significant amount of
 goodwill, which amount is tested for impairment at least annually. In addition, AAG and American may never realize the full value of their respective intangible assets or long-lived assets, causing them to record material impairment charges.
 </i></b>,
 <b>Risks Relating to AAGs Common Stock </b>,
 <b><i>The price of our common stock has recently been and may in the future be volatile. </i></b>,
 <b><i>We cannot guarantee that we will repurchase our common stock pursuant to our share repurchase program or continue to pay dividends
 on our common stock or that our capital deployment program will enhance long-term stockholder value. Our capital deployment program could increase the volatility of the price of our common stock and diminish our cash reserves. </i></b>,
 <b><i>Certain provisions of AAGs Certificate of Incorporation and Bylaws make it difficult for stockholders to change the
 composition of our Board of Directors and may discourage takeover attempts that some of our stockholders might consider beneficial. </i></b>,
 <b><i>AAGs Certificate of Incorporation and Bylaws include provisions that limit
 voting and acquisition and disposition of our equity interests. </i></b>,
 <b><i>In order to protect AAGs NOL Carryforwards and certain other tax attributes,
 AAGs Certificate of Incorporation includes certain limitations on acquisitions and dispositions of AAGs Common Stock, which may limit the liquidity of our common stock. </i></b>,
 <b><a name="tx829913_4"></a>ITEM 1B.  UNRESOLVED STAFF COMMENTS </b>,
 <b><a name="tx829913_5"></a>ITEM 2.  PROPERTIES </b>,
 <b>Flight Equipment </b>,
 <b><i>Mainline </i></b>,
 <b>Average Seating<br/>Capacity</b>,
 <b>Operating Aircraft</b>,
 <b>Non-<br/>Operating<br/>Aircraft (2)</b>,
 <b>Owned</b>,
 <b>Capital<br/>Leased</b>,
 <b>Operating<br/>Leased</b>,
 <b>Total</b>,
 <b>Average<br/>Age<br/>(Years)</b>,
 <b>In<br/>Temporary<br/>Storage (1)</b>,
 <b><i>Regional </i></b>,
 <b>Average Seating<br/>Capacity</b>,
 <b>Operating Aircraft</b>,
 <b>Non-<br/>Operating<br/>Aircraft (1)</b>,
 <b>Owned</b>,
 <b>Capital<br/>Leased</b>,
 <b>Operating<br/>Leased</b>,
 <b>Total</b>,
 <b>Average<br/>Age<br/>(Years)</b>,
 <b>In<br/>Temporary<br/>Storage</b>,
 <b><i>Aircraft Purchase Commitments and Lease Expirations </i></b>,
 <b>2015</b>,
 <b>2016</b>,
 <b>2017</b>,
 <b>2018</b>,
 <b>2019</b>,
 <b>2020 and<br/>Thereafter</b>,
 <b><i>Third-Party Regional Carriers </i></b>,
 <b>Number of Aircraft</b>,
 <b>Type of<br/>Aircraft</b>,
 <b>Carrier</b>,
 <b>American</b>,
 <b>US Airways</b>,
 <b><i>Other Information </i></b>,
 <b>Ground Properties </b>,
 <b><a name="tx829913_6"></a>ITEM 3.  LEGAL PROCEEDINGS </b>,
 <b><a name="tx829913_7"></a>ITEM 4.  MINE SAFETY DISCLOSURES </b>,
 <b><a name="tx829913_8"></a>PART II </b>,
 <b><a name="tx829913_9"></a>ITEM 5.  MARKET FOR AMERICAN AIRLINES GROUPS COMMON STOCK, RELATED STOCKHOLDER MATTERS AND ISSUER
 PURCHASES OF EQUITY SECURITIES </b>,
 <b>Stock Exchange Listing </b>,
 <b>Market Prices of Common Stock </b>,
 <b>Year Ended</b>,
 <b>December 31</b>,
 <b>Period</b>,
 <b>High</b>,
 <b>Low</b>,
 <b>2014</b>,
 <b>2013</b>,
 <b>Cash Dividends Paid </b>,
 <b>Stock Performance Graph </b>,
 <b>12/9/2013</b>,
 <b>12/31/2013</b>,
 <b>12/31/2014</b>,
 <b>Purchases of Equity Securities by the Issuer and Affiliated Purchasers </b>,
 <b>Period</b>,
 <b>Total number of</b>,
 <b>shares
 purchased</b>,
 <b>Average<br/>    price paid    <br/>per share</b>,
 <b>Total number of shares<br/>purchased as part of publicly<br/>announced
 plan or program (a)</b>,
 <b>Maximum dollar value
 of</b>,
 <b>shares that may be<br/>purchased under the plan or program</b>,
 <b>(in
 millions)</b>,
 <b>Ownership Restrictions </b>,
 <b><a name="tx829913_10"></a>ITEM 6.  SELECTED CONSOLIDATED FINANCIAL DATA </b>,
 <b>Selected Consolidated Financial Data of AAG </b>,
 <b>Year Ended December 31,</b>,
 <b>2014</b>,
 <b>2013</b>,
 <b>2012</b>,
 <b>2011</b>,
 <b>2010</b>,
 <b>(In millions, except share and per share data)</b>,
 <b>Reconciliation of GAAP to Non-GAAP Financial Measures </b>,
 <b>Year Ended December 31,</b>,
 <b>2014</b>,
 <b>2013</b>,
 <b>2012</b>,
 <b>2011</b>,
 <b>2010</b>,
 <b>(In millions)</b>,
 <b>Selected Consolidated Financial Data of American </b>,
 <b>Year Ended December 31,</b>,
 <b>2014</b>,
 <b>2013</b>,
 <b>2012</b>,
 <b>2011</b>,
 <b>2010</b>,
 <b>(In millions)</b>,
 <b><a name="tx829913_11"></a>ITEM 7. MANAGEMENTS DISCUSSION AND ANALYSIS OF FINANCIAL CONDITION
 AND RESULTS OF OPERATIONS </b>,
 <b><u>American Airlines Group </u></b>,
 <b>Year in Review </b>,
 <b>The U.S. Airline Industry </b>,
 <b>American Airlines Group
 </b>,
 <b>Year Ended<br/>December 31,<br/>2014</b>,
 <b>Year Ended December 31, 2013</b>,
 <b>Percent<br/>Change (1)</b>,
 <b>AAG</b>,
 <b>US Airways<br/>Group</b>,
 <b>Combined (3)</b>,
 <b>(In millions)</b>,
 <b>Special items:</b>,
 <b>December 31,</b>,
 <b>Better</b>,
 <b>(Worse)</b>,
 <b>2014</b>,
 <b>2013 (a)</b>,
 <b>December 31,</b>,
 <b>2014</b>,
 <b>December 31,</b>,
 <b>2013</b>,
 <b>(In millions)</b>,
 <b>Year Ended<br/>December 31, 2014</b>,
 <b>Year Ended December 31, 2013</b>,
 <b>AAG</b>,
 <b>US Airways<br/>Group</b>,
 <b>Combined</b>,
 <b>(In millions, except per ASM amounts)</b>,
 <b>(In cents)</b>,
 <b>AAGs Results of Operations </b>,
 <b>Year Ended December 31,</b>,
 <b>2014</b>,
 <b>2013</b>,
 <b>2012</b>,
 <b>Operating Statistics </b>,
 <b>Year Ended December 31,</b>,
 <b>Increase</b>,
 <b>(Decrease)</b>,
 <b>2014-2013</b>,
 <b>Increase</b>,
 <b>(Decrease)</b>,
 <b>2013-2012</b>,
 <b>2014</b>,
 <b>2013 (1)</b>,
 <b>2012 (1)</b>,
 <b>Mainline</b>,
 <b>Regional (j)</b>,
 <b>Total Mainline and Regional</b>,
 <b><i>2014 Compared to 2013 </i></b>,
 <b>Year Ended December 31,</b>,
 <b>$ Change</b>,
 <b>$ Change<br/>due to<br/>Merger</b>,
 <b>Change Excluding<br/>Merger Impact</b>,
 <b>    2014    </b>,
 <b>    2013    </b>,
 <b>    $    </b>,
 <b>    %    </b>,
 <b>(In millions, except percentage changes)</b>,
 <b>Year Ended December 31,</b>,
 <b>$ Change</b>,
 <b>$ Change</b>,
 <b>due
 to<br/>Merger</b>,
 <b>Change Excluding<br/>Merger Impact</b>,
 <b>    2014    </b>,
 <b>    2013    </b>,
 <b>    $    </b>,
 <b>    %    </b>,
 <b>(In millions, except percentage changes)</b>,
 <b>Year Ended December 31,</b>,
 <b>$ Change</b>,
 <b>$ Change</b>,
 <b>due
 to<br/>Merger</b>,
 <b>Change Excluding<br/>Merger Impact</b>,
 <b>    2014    </b>,
 <b>    2013    </b>,
 <b>    $    </b>,
 <b>    %    </b>,
 <b>(In millions, except percentage changes)</b>,
 <b>Year Ended December 31,</b>,
 <b>Increase<br/>(Decrease)</b>,
 <b>    2014    </b>,
 <b>    2013    </b>,
 <b>(In millions)</b>,
 <b>2013</b>,
 <b><i>2013 Compared to 2012 </i></b>,
 <b>Year Ended December 31,</b>,
 <b>$ Change</b>,
 <b>$ Change</b>,
 <b>due
 to<br/>Merger</b>,
 <b>Change Excluding<br/>Merger Impact</b>,
 <b>    2013    </b>,
 <b>    2012    </b>,
 <b>    $    </b>,
 <b>    %    </b>,
 <b>(In millions, except percentage changes)</b>,
 <b>Year Ended December 31,</b>,
 <b>$ Change</b>,
 <b>$ Change</b>,
 <b>due
 to<br/>Merger</b>,
 <b>Change Excluding<br/>Merger Impact</b>,
 <b>    2013    </b>,
 <b>    2012    </b>,
 <b>    $    </b>,
 <b>    %    </b>,
 <b>(In millions, except percentage changes)</b>,
 <b>Year Ended December 31,</b>,
 <b>$ Change</b>,
 <b>$ Change</b>,
 <b>due
 to<br/>Merger</b>,
 <b>Change Excluding<br/>Merger Impact</b>,
 <b>    2013    </b>,
 <b>    2012    </b>,
 <b>    $    </b>,
 <b>    %    </b>,
 <b>(In millions, except percentage changes)</b>,
 <b>2013</b>,
 <b>2012</b>,
 <b>Americans Results of Operations
 </b>,
 <b>Year Ended December 31,</b>,
 <b>2014</b>,
 <b>2013</b>,
 <b>2012</b>,
 <b><i>2014 Compared to 2013 </i></b>,
 <b>Year Ended December 31,</b>,
 <b>Percent<br/>Increase<br/>(Decrease)</b>,
 <b>    2014    </b>,
 <b>    2013    </b>,
 <b>(In millions, except percentage changes)</b>,
 <b>Year Ended December 31,</b>,
 <b>Percent<br/>Increase<br/>(Decrease)</b>,
 <b>    2014    </b>,
 <b>    2013    </b>,
 <b>(In millions, except percentage changes)</b>,
 <b>Year Ended December 31,</b>,
 <b>Percent<br/>Increase<br/>(Decrease)</b>,
 <b>    2014    </b>,
 <b>    2013    </b>,
 <b>(In millions, excluding percentage changes)</b>,
 <b>Year Ended December 31,</b>,
 <b>Increase<br/>(Decrease)</b>,
 <b>    2014    </b>,
 <b>    2013    </b>,
 <b>(In millions)</b>,
 <b>2013</b>,
 <b><i>2013 Compared to 2012
 </i></b>,
 <b>Year Ended December 31,</b>,
 <b>Percent<br/>Increase<br/>(Decrease)</b>,
 <b>    2013    </b>,
 <b>    2012    </b>,
 <b>(In millions, except percentage changes)</b>,
 <b>Year Ended December 31,</b>,
 <b>Percent<br/>Increase<br/>(Decrease)</b>,
 <b>    2013    </b>,
 <b>    2012    </b>,
 <b>(In millions, except percentage changes)</b>,
 <b>Year Ended December 31,</b>,
 <b>Percent<br/>Increase<br/>(Decrease)</b>,
 <b>    2013    </b>,
 <b>    2012    </b>,
 <b>(In millions, except percentage changes)</b>,
 <b>2013</b>,
 <b>2012</b>,
 <b>Liquidity and Capital Resources </b>,
 <b><i>Cash, Short-Term Investments and Restricted Cash </i></b>,
 <b>AAG</b>,
 <b>American</b>,
 <b>December 31,</b>,
 <b>December 31,</b>,
 <b>2014</b>,
 <b>2013</b>,
 <b>2014</b>,
 <b>2013</b>,
 <b><i>Share Repurchase Programs </i></b>,
 <b><i>Cash Dividends Paid </i></b>,
 <b><i>Sources and Uses of Cash </i></b>,
 <b><i><u>AAG </u></i></b>,
 <b><i><u>American </u></i></b>,
 <b><i>Commitments </i></b>,
 <b><i><u>Significant Indebtedness </u></i></b>,
 <b><i><u>Guarantees </u></i></b>,
 <b><i><u>Collateral Related Covenants </u></i></b>,
 <b>2014 Credit Facilities</b>,
 <b>2013 Credit Facilities</b>,
 <b>2013 Citicorp Credit Facility</b>,
 <b><i><u>Credit Ratings</u> </i></b>,
 <b>S&amp;P<br/>Local Issuer<br/>Credit Rating</b>,
 <b>Fitch<br/>Issuer Default<br/>Credit Rating</b>,
 <b>Moodys<br/>Corporate<br/>Family Rating</b>,

This is the information that I need for this project. I hope that the other reports will follow the same format, so that it is easy to scrape across the whole industry. Let us continue:

## Separate & Parse Document

In [10]:
searchstr = '('
for i in range(1,16):
    searchstr+=str(i)+'.|'

searchstr+='16.)'
searchstr

'(1.|2.|3.|4.|5.|6.|7.|8.|9.|10.|11.|12.|13.|14.|15.|16.)'

In [11]:
#test = r'(a>Item(\s|&#160;|&nbsp;)'+searchstr+'\.{0,1})|(>ITEM\s'+searchstr+')'

In [12]:
# Write the regex
#regex = re.compile(r'(a>Item(\s|&#160;|&nbsp;)'+searchstr+'\.{0,1})|(>ITEM\s'+searchstr+')')
#regex = re.compile(r'Overview')

# Use finditer to math the regex
#matches = regex.finditer(raw_10k)

In [19]:
matches = re.finditer("\/a>Item(\s|&#160;|&nbsp;)"+searchstr, raw_10k, re.IGNORECASE)
locations = [x for x in matches]
locations

[<re.Match object; span=(60523, 60538), match='/a>ITEM&#160;1.'>,
 <re.Match object; span=(261964, 261979), match='/a>ITEM&#160;1A'>,
 <re.Match object; span=(422769, 422784), match='/a>ITEM&#160;1B'>,
 <re.Match object; span=(423734, 423749), match='/a>ITEM&#160;2.'>,
 <re.Match object; span=(552226, 552241), match='/a>ITEM&#160;3.'>,
 <re.Match object; span=(563911, 563926), match='/a>ITEM&#160;4.'>,
 <re.Match object; span=(564782, 564797), match='/a>ITEM&#160;5.'>,
 <re.Match object; span=(598619, 598634), match='/a>ITEM&#160;6.'>,
 <re.Match object; span=(723646, 723661), match='/a>ITEM&#160;7.'>,
 <re.Match object; span=(1568708, 1568723), match='/a>ITEM&#160;7A'>,
 <re.Match object; span=(1614421, 1614436), match='/a>ITEM&#160;8A'>,
 <re.Match object; span=(3215477, 3215492), match='/a>ITEM&#160;8B'>,
 <re.Match object; span=(4331581, 4331596), match='/a>ITEM&#160;9.'>,
 <re.Match object; span=(4331976, 4331991), match='/a>ITEM&#160;9A'>,
 <re.Match object; span=(4353593, 4353608), match='/a>ITEM&#160;10'>,
 <re.Match object; span=(4355559, 4355574), match='/a>ITEM&#160;11'>,
 <re.Match object; span=(4356681, 4356696), match='/a>ITEM&#160;12'>,
 <re.Match object; span=(4357701, 4357716), match='/a>ITEM&#160;13'>,
 <re.Match object; span=(4358396, 4358411), match='/a>ITEM&#160;14'>,
 <re.Match object; span=(4359556, 4359571), match='/a>ITEM&#160;15'>]

In [20]:
temp = raw_10k[261964:422769]

In [23]:
temp[:500]

'/a>ITEM&#160;1A.&#160;&#160;RISK FACTORS </b></font></p>\n<p align="justify" style="margin-top:6px;margin-bottom:0px; text-indent:2%"><font size="2" style="font-family:Times New Roman">Below are certain risk factors that may affect our business, results of operations and financial condition, or the trading\nprice of our common stock or other securities. We caution the reader that these risk factors may not be exhaustive. We operate in a continually changing business environment, and new risks and '

In [24]:
h = html2text.HTML2Text()

In [192]:
h.handle(temp[:10000])

'>ITEM 15. EXHIBITS** | **AND FINANCIAL STATEMENT SCHEDULES**  \n  \n**Consolidated Financial Statements**\n\nThe following consolidated financial statements of American Airlines Group\nInc. and Independent Auditors\x92 Report are filed as part of this report:\n\n|  |  |  |  \n---|---|---|---|---  \n|  | **Page** |  \n|  \n  \nReport of Independent Registered Public Accounting Firm\n\n|  |  | 84 |  \n|  \n  \nConsolidated Statements of Operations for the Years Ended December 31, 2016,\n2015 and 2014\n\n|  |  | 85 |  \n|  \n  \nConsolidated Statements of Comprehensive Income for the Years Ended December\n31, 2016, 2015 and 2014\n\n|  |  | 86 |  \n|  \n  \nConsolidated Balance Sheets at December 31, 2016 and 2015\n\n|  |  | 87 |  \n|  \n  \nConsolidated Statements of Cash Flows for the Years Ended December 31, 2016,\n2015 and 2014\n\n|  |  | 88 |  \n|  \n  \nConsolidated Statements of Stockholders\x92 Equity (Deficit) for the Years Ended\nDecember 31, 2016, 2015 and 2014\n\n|  |  | 89 |  \n|  \n  \nNotes to Consolidated Financial Statements\n\n|  |  | 90 |  \n  \nThe following consolidated financial statements of American Airlines, Inc. and\nIndependent Auditors\x92 Report are filed as part of this report:\n\n|  |  |  |  \n---|---|---|---|---  \n|  | **Page** |  \n|  \n  \nReport of Independent Registered Public Accounting Firm\n\n|  |  | 136 |  \n|  \n  \nConsolidated Statements of Operations for the Years Ended December 31, 2016,\n2015 and 2014\n\n|  |  | 137 |  \n|  \n  \nConsolidated Statements of Comprehensive Income for the Years Ended December\n31, 2016, 2015 and 2014\n\n|  |  | 138 |  \n|  \n  \n<font color="#435363"\n\n'

In [194]:
tempsoup = BeautifulSoup(temp, 'html.parser')
goods = tempsoup.find_all('p')
[x.text for x in goods][1]

'The\nfollowing consolidated financial statements of American Airlines Group Inc. and Independent Auditors’ Report are filed as part of this report: '

Now, we will do all of them

In [16]:
starts = [0]+[locations[i].start() for i in range(len(locations))] + [len(raw_10k)]
starts

[0,
 60523,
 261964,
 422769,
 423734,
 552226,
 563911,
 564782,
 598619,
 723646,
 1568708,
 1614421,
 3215477,
 4331581,
 4331976,
 4353593,
 4355559,
 4356681,
 4357701,
 4358396,
 4359556,
 4575093]

In [17]:
sections = {}

for i in range(len(starts)-1):
    temp = raw_10k[starts[i]:starts[i+1]]
    tempsoup = BeautifulSoup(temp, 'html.parser')
    goods = tempsoup.find_all('p')
    sections[i] = [x.text for x in goods]

## Validation

In [18]:
''.join(sections[2])[:5000]

'Below are certain risk factors that may affect our business, results of operations and financial condition, or the trading\nprice of our common stock or other securities. We caution the reader that these risk factors may not be exhaustive. We operate in a continually changing business environment, and new risks and uncertainties emerge from time to time. Management\ncannot predict such new risks and uncertainties, nor can it assess the extent to which any of the risk factors below or any such new risks and uncertainties, or any combination thereof, may impact our business. Risk Factors Relating to the Company and Industry-Related Risks We could experience significant operating losses in the future. For a number of reasons, including those addressed in these risk factors, we might fail to maintain profitability and might experience significant losses. In particular, the condition of the economy, the\nlevel and volatility of fuel prices, the state of travel demand and intense competition in the airline industry have had and will continue to have an impact on our operating results, and may increase the risk that we will experience losses.\nDownturns in economic conditions adversely affect our business. Due to the discretionary nature of business and leisure travel spending, airline industry revenues are heavily influenced\nby the condition of the U.S. economy and economies in other regions of the world. Unfavorable conditions in these broader economies have resulted, and may result in the future, in decreased passenger demand for air travel and changes in booking\npractices, both of which in turn have had, and may have in the future, a strong negative effect on our revenues. In addition, during challenging economic times, actions by our competitors to increase their revenues can have an adverse impact on our\nrevenues. See “The airline industry is intensely competitive and dynamic” below. Certain labor agreements to which we are a party limit our ability to reduce the number of aircraft in operation, and the utilization of such aircraft,\nbelow certain levels. As a result, we may not be able to optimize the number of aircraft in operation in response to a decrease in passenger demand for air travel. Our business is dependent on the price and availability of aircraft fuel. Continued periods of high volatility in fuel costs, increased fuel prices and significant disruptions in the supply of\naircraft fuel could have a significant negative impact on our operating results and liquidity. Our\noperating results are materially impacted by changes in the availability, price volatility and cost of aircraft fuel, which represents one of the largest single cost items in our business. Jet fuel market prices have fluctuated substantially over\nthe past several years and prices continued to be volatile in 2014. Because of the amount of fuel needed to\noperate our business, even a relatively small increase in the price of fuel can have a material adverse aggregate effect on our operating results and liquidity. Due to the competitive nature of the airline industry and unpredictability of the\nmarket, we can offer no assurance that we may be able to increase our fares, impose fuel surcharges or otherwise increase revenues sufficiently to offset fuel price increases. Although we are currently able to obtain adequate supplies of aircraft fuel, we cannot predict the future availability,\nprice volatility or cost of aircraft fuel. Natural disasters, political disruptions or wars involving oil-producing countries, changes in fuel-related governmental policy, the strength of the U.S. dollar against foreign currencies, changes in access\nto petroleum product pipelines and terminals, speculation in the energy futures markets, changes in aircraft fuel production capacity, environmental concerns and other unpredictable events may result in fuel supply shortages, additional fuel price\nvolatility and cost increases in the future. We have a large number of older aircraft in our fleet, and these\naircraft are not as fuel efficient as more recent models of aircraft, including those we have on order. We intend to continue to execute our fleet renewal plans to, \xa030 \n\namong other things, improve the fuel efficiency of our fleet, and we are dependent on a limited number of major aircraft manufacturers to deliver aircraft on schedule. If we experience delays in\ndelivery of the more fuel efficient aircraft that we have on order, we will be adversely affected. Our\naviation fuel purchase contracts generally do not provide meaningful price protection against increases in fuel costs. Prior to the closing of the Merger, we sought to manage the risk of fuel price increases by using derivative contracts. During the\nsecond quarter of 2014, we sold our portfolio of fuel hedging contracts that were scheduled to settle on or after June\xa030, 2014. We have not entered into any transactions to hedge our fuel consumption since December\xa09, 2013 and,\naccordingly, as of December\xa031'

YES ! Now, let's see if we can extrapolate to all files for AAL:

In [166]:
AAL_10K = {}
pos_dats = {}

for year in pulls:
    

    f = open("sec-edgar-filings/AAL/10-K/"+year+"/filing-details.html", "r")
    raw_10k = f.read()

    matches = re.finditer("\/*>ITEM(\s|&#160;|&nbsp;)"+searchstr+'\.{0,1}', raw_10k)
    #matches = re.finditer("\/*>Item(\s|&#160;|&nbsp;)"+searchstr, raw_10k, re.IGNORECASE)
    locations = [x for x in matches]
    
    
    # Create the dataframe
    test_df = pd.DataFrame([(x.group(), x.start(), x.end()) for x in locations])

    test_df.columns = ['item', 'start', 'end']
    test_df['item'] = test_df.item.str.lower()
    
    # Get rid of unnesesary charcters from the dataframe
    test_df.replace('&#160;',' ',regex=True,inplace=True)
    test_df.replace('&nbsp;',' ',regex=True,inplace=True)
    test_df.replace(' ','',regex=True,inplace=True)
    test_df.replace('\.','',regex=True,inplace=True)
    test_df.replace('>','',regex=True,inplace=True)
    test_df.replace('\(','',regex=True,inplace=True)
    test_df.replace('\)','',regex=True,inplace=True)
    test_df.replace('\n','',regex=True,inplace=True)
    test_df.replace('\xa0','',regex=True,inplace=True)
    
    # Drop duplicates, keep last
    pos_dat = test_df.sort_values('start', ascending=True).drop_duplicates(subset=['item'], keep='last')
    
    # Set item as the dataframe index
    pos_dat.set_index('item', inplace=True)
    pos_dats[year] = pos_dat

    #starts = [0]+[locations[i].start() for i in range(len(locations))] + [len(raw_10k)]

    sections = {}

    #for i in range(len(starts)-1):
    #    temp = raw_10k[starts[i]:starts[i+1]]
        #tempsoup = BeautifulSoup(temp, 'html.parser')
        #goods = tempsoup.find_all('font')
        #sections[i] = [x.text for x in goods]
    #    sections[i] = h.handle(temp)
    
    for i in range(len(pos_dat.index)-1):
        temp = raw_10k[pos_dat['start'][i]:pos_dat['start'][i+1]]
        sections[pos_dat.index[i]] = h.handle(temp)
        
    
    AAL_10K[year[11:13]] = sections

In [176]:
a = pd.DataFrame()

for year in AAL_10K.keys():
    b = pd.DataFrame([len(x) for x in AAL_10K[year].values()], index = AAL_10K[year].keys(), columns=[year])
    a = pd.concat([a,b], axis=1, join='outer')

In [183]:
a.sort_index()

,08,20,06,03,05,04,10,11,18,15,12,21,16,14,07,19,09,13,17
item1,47896.0,47862.0,41816.0,65966.0,47521.0,48475.0,49563.0,44080.0,44565.0,87465.0,42756.0,79490.0,70639.0,88909.0,39454.0,47775.0,49212.0,37884.0,46995.0
item10,496.0,1199.0,402.0,309.0,403.0,403.0,702.0,690.0,1283.0,1494.0,22953.0,1242.0,1251.0,1695.0,402.0,1304.0,496.0,839.0,1253.0
item11,269.0,518.0,175.0,177.0,176.0,212.0,269.0,256.0,450.0,645.0,128007.0,561.0,645.0,1186.0,175.0,518.0,269.0,385.0,398.0
item12,1563.0,446.0,2337.0,217.0,2525.0,2635.0,1412.0,1824.0,471.0,578.0,5882.0,489.0,578.0,647.0,2042.0,446.0,1672.0,502.0,418.0
item13,307.0,444.0,235.0,201.0,236.0,200.0,291.0,280.0,444.0,392.0,2609.0,487.0,392.0,463.0,235.0,444.0,307.0,463.0,392.0
item14,307.0,401.0,203.0,31582.0,212.0,241.0,318.0,305.0,401.0,371.0,3323.0,455.0,371.0,420.0,203.0,401.0,307.0,427.0,371.0
item15,NaN,135071.0,NaN,NaN,NaN,NaN,NaN,NaN,145785.0,NaN,NaN,142137.0,NaN,NaN,NaN,127605.0,NaN,NaN,2764.0
item1a,27439.0,110805.0,24374.0,NaN,NaN,NaN,43394.0,47592.0,96492.0,102757.0,61747.0,143009.0,101127.0,95237.0,25823.0,109726.0,35648.0,99291.0,89551.0
item1b,242.0,254.0,146.0,NaN,NaN,NaN,237.0,226.0,257.0,199.0,168.0,308.0,186.0,221.0,146.0,257.0,242.0,224.0,186.0
item2,7531.0,9459.0,9198.0,7317.0,8719.0,10295.0,7506.0,8428.0,9316.0,11393.0,8329.0,9961.0,11635.0,11512.0,8802.0,7774.0,7448.0,7394.0,11612.0
item3,14752.0,6129.0,13918.0,12702.0,13080.0,14431.0,14871.0,11038.0,6536.0,10168.0,14620.0,327.0,8620.0,9973.0,16067.0,5471.0,14116.0,9183.0,6844.0
item4,3674.0,154.0,2961.0,3437.0,2851.0,2710.0,3688.0,4526.0,157.0,110.0,81.0,194.0,110.0,260.0,3438.0,154.0,3675.0,264.0,133.0
item5,1097.0,7772.0,1053.0,3720.0,1158.0,1218.0,1179.0,1276.0,7666.0,11475.0,1685.0,8431.0,12043.0,6598.0,1055.0,6819.0,1185.0,1855.0,8833.0
item6,64628.0,12203.0,65221.0,75348.0,84611.0,84193.0,81825.0,95574.0,14022.0,23165.0,113396.0,13665.0,25214.0,173973.0,58250.0,13796.0,85162.0,86267.0,15899.0
item7,5642.0,74944.0,6029.0,142938.0,6174.0,7271.0,7334.0,7320.0,120133.0,195943.0,7642.0,89615.0,161896.0,16786.0,5877.0,114685.0,7610.0,7778.0,121418.0
item7a,NaN,6235.0,NaN,NaN,NaN,NaN,NaN,NaN,4533.0,16334.0,NaN,6923.0,10923.0,NaN,NaN,4530.0,NaN,NaN,4612.0
item8,118773.0,NaN,115159.0,NaN,128708.0,135226.0,128494.0,144917.0,NaN,NaN,184242.0,NaN,NaN,NaN,122651.0,NaN,128831.0,197352.0,NaN
item8a,NaN,157484.0,NaN,NaN,NaN,NaN,NaN,NaN,155288.0,278545.0,NaN,229813.0,273170.0,241321.0,NaN,164339.0,NaN,NaN,184663.0
item8b,NaN,150950.0,NaN,NaN,NaN,NaN,NaN,NaN,148482.0,216741.0,NaN,209790.0,224310.0,191290.0,NaN,157623.0,NaN,NaN,173688.0
item9,201.0,165.0,107.0,129.0,118.0,108.0,201.0,188.0,165.0,112.0,128.0,207.0,112.0,183.0,107.0,165.0,201.0,186.0,112.0
item9a,7061.0,14025.0,7375.0,NaN,7442.0,1164.0,7006.0,6976.0,13750.0,13329.0,7196.0,13746.0,13249.0,16569.0,7471.0,14507.0,7061.0,7192.0,13041.0
item9b,NaN,109.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152.0,NaN,942.0,NaN,NaN,NaN,NaN,NaN

In [187]:
# Spot Check
AAL_10K['12']['item4']

'>ITEM 4.** | **REMOVED AND RESERVED**  \n---|---  \n  \n28\n\n* * *\n\n**PART II**\n\n<b\n\n'

In [189]:
# Export the results
with open('AAL_parsed.pickle', 'wb') as handle:
    pickle.dump(AAL_10K, handle, protocol=pickle.HIGHEST_PROTOCOL)

# Scratchpad

Ignore the stuff below this

In [156]:
year = list(pos_dats.keys())[0]

f = open("sec-edgar-filings/AAL/10-K/"+year+"/filing-details.html", "r")
raw_10k = f.read()

matches = re.finditer("\/*>ITEM(\s|&#160;|&nbsp;)"+searchstr+'\.{0,1}', raw_10k)
#matches = re.finditer("\/*>Item(\s|&#160;|&nbsp;)"+searchstr, raw_10k, re.IGNORECASE)
locations = [x for x in matches]


# Create the dataframe
test_df = pd.DataFrame([(x.group(), x.start(), x.end()) for x in locations])

test_df.columns = ['item', 'start', 'end']
test_df['item'] = test_df.item.str.lower()

# Get rid of unnesesary charcters from the dataframe
test_df.replace('&#160;',' ',regex=True,inplace=True)
test_df.replace('&nbsp;',' ',regex=True,inplace=True)
test_df.replace(' ','',regex=True,inplace=True)
test_df.replace('\.','',regex=True,inplace=True)
test_df.replace('>','',regex=True,inplace=True)
test_df.replace('(','',regex=False,inplace=True)
test_df.replace(')','',regex=False,inplace=True)
test_df.replace('\n','',regex=True,inplace=True)
test_df.replace('\xa0','',regex=True,inplace=True)

In [155]:
test_df.replace('\n','',regex=True)

      item    start      end
0    item1    17930    17938
1   item1a   107309   107318
2   item1b   162576   162585
3    item2   163391   163399
4    item3   329152   329160
5    item4   348888   348896
6    item5   361380   361388
7    item6   382480   382488
8    item7   432850   432858
9   item7(   708774   708782
10   item8   718193   718201
11   item9  2038862  2038870
12  item9a  2039581  2039590
13  item10  2056495  2056504
14  item11  2057556  2057565
15  item12  2058367  2058376
16  item13  2072011  2072020
17  item14  2073620  2073629
18  item15  2074953  2074962

'0000950134-07-003888'

In [40]:
f = open("sec-edgar-filings/AAL/10-K/"+pulls[2]+"/filing-details.html", "r")
raw_10k = f.read()

In [41]:
raw_10k[:500]

'<html><body><document>\n<type>10-K\n<sequence>1\n<filename>d33303e10vk.htm\n<description>FORM 10-K\n<text>\n<title>e10vk</title>\n<!-- PAGEBREAK -->\n<h5 align="left" style="page-break-before:always"><a href="#toc">Table of Contents</a></h5><p>\n</p><div style="font-family: \'Times New Roman\',Times,serif">\n<div style="width: 100%; border-bottom: 2pt solid black; font-size: 1pt">&#160;</div>\n<div style="width: 100%; border-bottom: 1pt solid black; font-size: 1pt">&#160;</div>\n<div align="center" style="fon'

In [46]:
matches = re.finditer("\/*>ITEM(\s|&#160;|&nbsp;)"+searchstr, raw_10k)
locations = [x for x in matches]

In [47]:
locations

[<re.Match object; span=(8971, 8979), match='>ITEM 1.'>,
 <re.Match object; span=(9046, 9054), match='>ITEM 1A'>,
 <re.Match object; span=(9126, 9134), match='>ITEM 1B'>,
 <re.Match object; span=(9219, 9227), match='>ITEM 2.'>,
 <re.Match object; span=(9296, 9304), match='>ITEM 3.'>,
 <re.Match object; span=(9380, 9388), match='>ITEM 4.'>,
 <re.Match object; span=(9555, 9563), match='>ITEM 5.'>,
 <re.Match object; span=(9695, 9703), match='>ITEM 6.'>,
 <re.Match object; span=(9798, 9806), match='>ITEM 7.'>,
 <re.Match object; span=(9955, 9963), match='>ITEM 7('>,
 <re.Match object; span=(10083, 10091), match='>ITEM 8.'>,
 <re.Match object; span=(10183, 10191), match='>ITEM 9.'>,
 <re.Match object; span=(10334, 10342), match='>ITEM 9A'>,
 <re.Match object; span=(10483, 10491), match='>ITEM 10'>,
 <re.Match object; span=(10601, 10609), match='>ITEM 11'>,
 <re.Match object; span=(10691, 10699), match='>ITEM 12'>,
 <re.Match object; span=(10821, 10829), match='>ITEM 13'>,
 <re.Match object; span=(10935, 10943), match='>ITEM 14'>,
 <re.Match object; span=(11098, 11106), match='>ITEM 15'>,
 <re.Match object; span=(15280, 15288), match='>ITEM 1.'>,
 <re.Match object; span=(69562, 69570), match='>ITEM 1A'>,
 <re.Match object; span=(103921, 103929), match='>ITEM 1B'>,
 <re.Match object; span=(104282, 104290), match='>ITEM 2.'>,
 <re.Match object; span=(147437, 147445), match='>ITEM 3.'>,
 <re.Match object; span=(163233, 163241), match='>ITEM 4.'>,
 <re.Match object; span=(168902, 168910), match='>ITEM 5.'>,
 <re.Match object; span=(173620, 173628), match='>ITEM 6.'>,
 <re.Match object; span=(187250, 187258), match='>ITEM 7.'>,
 <re.Match object; span=(309402, 309410), match='>ITEM 7('>,
 <re.Match object; span=(316785, 316793), match='>ITEM 8.'>,
 <re.Match object; span=(696726, 696734), match='>ITEM 9.'>,
 <re.Match object; span=(697058, 697066), match='>ITEM 9A'>,
 <re.Match object; span=(708043, 708051), match='>ITEM 10'>,
 <re.Match object; span=(708694, 708702), match='>ITEM 11'>,
 <re.Match object; span=(709143, 709151), match='>ITEM 12'>,
 <re.Match object; span=(718129, 718137), match='>ITEM 13'>,
 <re.Match object; span=(718840, 718848), match='>ITEM 14'>,
 <re.Match object; span=(719437, 719445), match='>ITEM 15'>]

In [55]:
# Create the dataframe
test_df = pd.DataFrame([(x.group(), x.start(), x.end()) for x in locations])

test_df.columns = ['item', 'start', 'end']
test_df['item'] = test_df.item.str.lower()

# Display the dataframe
test_df.head()

       item  start   end
0  >item 1.   8971  8979
1  >item 1a   9046  9054
2  >item 1b   9126  9134
3  >item 2.   9219  9227
4  >item 3.   9296  9304

In [53]:
# Get rid of unnesesary charcters from the dataframe
test_df.replace('&#160;',' ',regex=True,inplace=True)
test_df.replace('&nbsp;',' ',regex=True,inplace=True)
test_df.replace(' ','',regex=True,inplace=True)
test_df.replace('\.','',regex=True,inplace=True)
test_df.replace('>','',regex=True,inplace=True)

# display the dataframe
test_df.head()

     item  start   end
0   item1   8971  8979
1  item1a   9046  9054
2  item1b   9126  9134
3   item2   9219  9227
4   item3   9296  9304

In [54]:
# Drop duplicates
pos_dat = test_df.sort_values('start', ascending=True).drop_duplicates(subset=['item'], keep='last')

# Display the dataframe
pos_dat

      item   start     end
19   item1   15280   15288
20  item1a   69562   69570
21  item1b  103921  103929
22   item2  104282  104290
23   item3  147437  147445
24   item4  163233  163241
25   item5  168902  168910
26   item6  173620  173628
27   item7  187250  187258
28  item7(  309402  309410
29   item8  316785  316793
30   item9  696726  696734
31  item9a  697058  697066
32  item10  708043  708051
33  item11  708694  708702
34  item12  709143  709151
35  item13  718129  718137
36  item14  718840  718848
37  item15  719437  719445

In [200]:
starts = [0]+[locations[i].start() for i in range(len(locations))] + [len(raw_10k)]
starts

[0,
 1086087,
 1237001,
 1403729,
 1404704,
 1604605,
 1613114,
 1614256,
 1656844,
 1861130,
 2486957,
 2498116,
 4720049,
 6855055,
 6855526,
 6882426,
 6883116,
 6884894,
 6885703,
 6886440,
 6887175,
 6888387,
 7212307,
 7250228]

In [219]:
for i in range(len(starts)-1):
    temp = raw_10k[starts[i]:starts[i+1]]
    tempsoup = BeautifulSoup(temp, 'html.parser')
    tempsoup.prettify()
    goods = tempsoup.find_all('div')
    sections[i] = [x.text for x in goods]

In [226]:
[len(x) for x in sections.values()]

[351,
 502,
 352,
 9,
 886,
 15,
 11,
 162,
 880,
 2387,
 26,
 6773,
 6205,
 3,
 79,
 6,
 4,
 3,
 3,
 3,
 11,
 845,
 169]

In [122]:
document = soup.html.find_all()

el = ['html',]  # we already include the html tag
for n in document:
    if n.name not in el:
        el.append(n.name)

print(el)

['html', 'body', 'document', 'type', 'sequence', 'filename', 'description', 'text', 'title', 'div', 'hr', 'br', 'font', 'table', 'tr', 'td', 'a']

In [190]:
print(soup.findAll('div')[3].text)

Washington,
D.C. 20549

In [715]:
type(raw_10k)

str

In [710]:
# Write a for loop to print the matches
for match in matches:
    print(match)

In [711]:
raw_10k[30355:30555]

'p style="margin-left:4.50em; text-indent:-4.50em"><font size="2" style="font-family:Times New Roman">Item&#160;1.&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</font></p></td>\n<td valign="bottom"><f'

In [703]:
raw_10k[60000:60895]

'idth="100%"/>\n<h5 align="left"><a href="#toc">Table of Contents</a></h5>\n<p align="center" style="margin-top:0px;margin-bottom:0px"><font size="2" style="font-family:Times New Roman"><b><a name="tx829913_1"></a>PART I </b></font></p>\n<p style="font-size:12px;margin-top:0px;margin-bottom:0px">&#160;</p>\n<table border="0" cellpadding="0" cellspacing="0" style="BORDER-COLLAPSE:COLLAPSE" width="100%">\n<tr>\n<td align="left" valign="top" width="9%"><font size="2" style="font-family:Times New Roman"><b><a name="tx829913_2"></a>ITEM&#160;1.&#160;&#160;BUSINESS</b></font></td>\n<td align="left" valign="top"><font size="2" style="font-family:Times New Roman"><b></b></font></td></tr></table> <p style="margin-top:6px;margin-bottom:0px"><font size="2" style="font-family:Times New Roman"><b>Overview </b></font></p>\n<p align="justify" style="margin-top:6px;margin-bottom:0px; text-indent:2%"><font s'

In [604]:
document = {}

# Create a loop to go through each section type and save only the 10-K section in the dictionary
for doc_type, doc_start, doc_end in zip(doc_types, doc_start_is, doc_end_is):
    if doc_type == '10-K':
        document[doc_type] = raw_10k[doc_start:doc_end]

In [605]:
# display excerpt the document
document['10-K'][0:500]

'\n<type>10-K\n<sequence>1\n<filename>d829913d10k.htm\n<description>FORM 10-K\n<text>\n<title>Form 10-K</title>\n<h5 align="left"><a href="#toc">Table of Contents</a></h5>\n<p style="line-height:4px;margin-top:0px;margin-bottom:0px;border-bottom:2pt solid #000000">&#160;</p>\n<p style="line-height:3px;margin-top:0px;margin-bottom:2px;border-bottom:0.5pt solid #000000">&#160;</p> <p align="center" style="margin-top:1px;margin-bottom:0px"><font size="2" style="font-family:Times New Roman"><b>UNITED STATES S'

In [628]:
doc_types

['10-K']

In [630]:
soup = BeautifulSoup(document['10-K'], 'lxml')

In [634]:
soup.findAll('b')[106:110]

[<b><a name="tx829913_3"></a>ITEM 1A.  RISK FACTORS </b>,
 <b>Risk Factors Relating to the Company and Industry-Related Risks </b>,
 <b><i>We could experience significant operating losses in the future. </i></b>,
 <b><i>Downturns in economic conditions adversely affect our business. </i></b>]

In [638]:
# Write the regex
regex = re.compile(r'(>Item(\s|&#160;|&nbsp;)(1A|1B|7A|7|8)\.{0,1})|(ITEM\s(1A|1B|7A|7|8))')

# Use finditer to math the regex
matches = regex.finditer(document['10-K'])

# Write a for loop to print the matches
for match in matches:
    print(match)

<re.Match object; span=(31194, 31208), match='>Item&#160;1A.'>
<re.Match object; span=(31937, 31951), match='>Item&#160;1B.'>
<re.Match object; span=(37030, 37043), match='>Item&#160;7.'>
<re.Match object; span=(37875, 37889), match='>Item&#160;7A.'>
<re.Match object; span=(38666, 38678), match='>Item&#160;8'>
<re.Match object; span=(39487, 39499), match='>Item&#160;8'>

In [640]:
els = soup.select('a')
asdf = []
for el in els:
    asdf.append(el.get_text())

In [645]:
document['10-K'][31194:32194]

'>Item&#160;1A.&#160;&#160;&#160;&#160;</font></p></td>\n<td valign="bottom"><font size="1">&#160;</font></td>\n<td valign="top"><font size="2" style="font-family:Times New Roman"><a href="#tx829913_3">Risk Factors</a></font></td>\n<td valign="bottom"><font size="1">&#160;&#160;</font></td>\n<td nowrap="" valign="bottom"><font size="2" style="font-family:Times New Roman">&#160;</font></td>\n<td align="right" nowrap="" valign="bottom"><font size="2" style="font-family:Times New Roman">30</font></td>\n<td nowrap="" valign="bottom"><font size="2" style="font-family:Times New Roman">&#160;&#160;</font></td></tr>\n<tr>\n<td nowrap="" valign="top"> <p style="margin-left:4.50em; text-indent:-4.50em"><font size="2" style="font-family:Times New Roman">Item&#160;1B.&#160;&#160;&#160;&#160;&#160;</font></p></td>\n<td valign="bottom"><font size="1">&#160;</font></td>\n<td valign="top"><font size="2" style="font-family:Times New Roman"><a href="#tx829913_4">Unresolved Staff Comments</a></font></td>\n<td valign'

In [619]:
# Matches
matches = regex.finditer(document['10-K'])

# Create the dataframe
test_df = pd.DataFrame([(x.group(), x.start(), x.end()) for x in matches])

test_df.columns = ['item', 'start', 'end']
test_df['item'] = test_df.item.str.lower()

# Display the dataframe
test_df.head()

             item  start    end
0  >item&#160;1a.  31194  31208
1  >item&#160;1b.  31937  31951
2   >item&#160;7.  37030  37043
3  >item&#160;7a.  37875  37889
4    >item&#160;8  38666  38678

In [620]:
raw_10k[31216:31230]

'>Item&#160;1A.'

In [621]:
# Get rid of unnesesary charcters from the dataframe
test_df.replace('&#160;',' ',regex=True,inplace=True)
test_df.replace('&nbsp;',' ',regex=True,inplace=True)
test_df.replace(' ','',regex=True,inplace=True)
test_df.replace('\.','',regex=True,inplace=True)
test_df.replace('>','',regex=True,inplace=True)

# display the dataframe
test_df.head()

     item  start    end
0  item1a  31194  31208
1  item1b  31937  31951
2   item7  37030  37043
3  item7a  37875  37889
4   item8  38666  38678

In [622]:
# Drop duplicates
pos_dat = test_df.sort_values('start', ascending=True).drop_duplicates(subset=['item'], keep='last')

# Display the dataframe
pos_dat

     item  start    end
0  item1a  31194  31208
1  item1b  31937  31951
2   item7  37030  37043
3  item7a  37875  37889
5   item8  39487  39499

In [623]:
# Set item as the dataframe index
pos_dat.set_index('item', inplace=True)

# display the dataframe
pos_dat

        start    end
item
item1a  31194  31208
item1b  31937  31951
item7   37030  37043
item7a  37875  37889
item8   39487  39499

In [625]:
# Get Item 1a
item_1_raw = document['10-K'][pos_dat['start'].loc['item1a']:pos_dat['start'].loc['item1b']]

# Get Item 7
#item_7_raw = raw_10k[pos_dat['start'].loc['item7']:pos_dat['start'].loc['item7a']]

# Get Item 7a
#item_7a_raw = raw_10k[pos_dat['start'].loc['item7a']:pos_dat['start'].loc['item8']]

In [626]:
soup1 = BeautifulSoup(item_1a_raw, 'html.parser')

In [627]:
raw_10k[31216:31959]

'>Item&#160;1A.&#160;&#160;&#160;&#160;</font></p></td>\n<td valign="bottom"><font size="1">&#160;</font></td>\n<td valign="top"><font size="2" style="font-family:Times New Roman"><a href="#tx829913_3">Risk Factors</a></font></td>\n<td valign="bottom"><font size="1">&#160;&#160;</font></td>\n<td nowrap="" valign="bottom"><font size="2" style="font-family:Times New Roman">&#160;</font></td>\n<td align="right" nowrap="" valign="bottom"><font size="2" style="font-family:Times New Roman">30</font></td>\n<td nowrap="" valign="bottom"><font size="2" style="font-family:Times New Roman">&#160;&#160;</font></td></tr>\n<tr>\n<td nowrap="" valign="top"> <p style="margin-left:4.50em; text-indent:-4.50em"><font size="2" style="font-family:Times New Roman"'

In [585]:
goods = soup1.find_all('b')
[x.text for x in goods]

[]

In [550]:
soup.find('div')

In [491]:
# kill all script and style elements
for script in soup(["script", "style"]):
    script.extract()    # rip it out

# get text
text = soup.get_text()

In [492]:
text[:5000]

'0001193125-15-061145.txt : 20150225\n0001193125-15-061145.hdr.sgml : 20150225\n20150225080234\nACCESSION NUMBER:\t\t0001193125-15-061145\nCONFORMED SUBMISSION TYPE:\t10-K\nPUBLIC DOCUMENT COUNT:\t\t20\nCONFORMED PERIOD OF REPORT:\t20141231\nFILED AS OF DATE:\t\t20150225\nDATE AS OF CHANGE:\t\t20150225\n\nFILER:\n\n\tCOMPANY DATA:\t\n\t\tCOMPANY CONFORMED NAME:\t\t\tAmerican Airlines Group Inc.\n\t\tCENTRAL INDEX KEY:\t\t\t0000006201\n\t\tSTANDARD INDUSTRIAL CLASSIFICATION:\tAIR TRANSPORTATION, SCHEDULED [4512]\n\t\tIRS NUMBER:\t\t\t\t751825172\n\t\tSTATE OF INCORPORATION:\t\t\tDE\n\t\tFISCAL YEAR END:\t\t\t1231\n\n\tFILING VALUES:\n\t\tFORM TYPE:\t\t10-K\n\t\tSEC ACT:\t\t1934 Act\n\t\tSEC FILE NUMBER:\t001-08400\n\t\tFILM NUMBER:\t\t15645918\n\n\tBUSINESS ADDRESS:\t\n\t\tSTREET 1:\t\t4333 AMON CARTER BLVD\n\t\tCITY:\t\t\tFORT WORTH\n\t\tSTATE:\t\t\tTX\n\t\tZIP:\t\t\t76155\n\t\tBUSINESS PHONE:\t\t8179631234\n\n\tMAIL ADDRESS:\t\n\t\tSTREET 1:\t\t4333 AMON CARTER BLVD\n\t\tCITY:\t\t\tFORT WORTH\n\t\tSTATE:\t\t\tTX\n\t\tZIP:\t\t\t75261-9616\n\n\tFORMER COMPANY:\t\n\t\tFORMER CONFORMED NAME:\tAMR CORP\n\t\tDATE OF NAME CHANGE:\t19920703\n\nFILER:\n\n\tCOMPANY DATA:\t\n\t\tCOMPANY CONFORMED NAME:\t\t\tAMERICAN AIRLINES INC\n\t\tCENTRAL INDEX KEY:\t\t\t0000004515\n\t\tSTANDARD INDUSTRIAL CLASSIFICATION:\tAIR TRANSPORTATION, SCHEDULED [4512]\n\t\tIRS NUMBER:\t\t\t\t131502798\n\t\tSTATE OF INCORPORATION:\t\t\tDE\n\t\tFISCAL YEAR END:\t\t\t1231\n\n\tFILING VALUES:\n\t\tFORM TYPE:\t\t10-K\n\t\tSEC ACT:\t\t1934 Act\n\t\tSEC FILE NUMBER:\t001-02691\n\t\tFILM NUMBER:\t\t15645919\n\n\tBUSINESS ADDRESS:\t\n\t\tSTREET 1:\t\t4333 AMON CARTER BLVD\n\t\tCITY:\t\t\tFT WORTH\n\t\tSTATE:\t\t\tTX\n\t\tZIP:\t\t\t76155\n\t\tBUSINESS PHONE:\t\t8179631234\n\n\tMAIL ADDRESS:\t\n\t\tSTREET 1:\t\tP O BOX 619616 MD5661\n\t\tCITY:\t\t\tDALLAS FORT WORTH AI\n\t\tSTATE:\t\t\tTX\n\t\tZIP:\t\t\t75261-9616\n\n\tFORMER COMPANY:\t\n\t\tFORMER CONFORMED NAME:\tAMERICAN AIRWAYS INC\n\t\tDATE OF NAME CHANGE:\t19670629\n\n\n10-K\n1\nd829913d10k.htm\nFORM 10-K\n\n\nForm 10-K\n\n\nTable of Contents\n\xa0\n\xa0 UNITED STATES SECURITIES AND\nEXCHANGE COMMISSION  Washington, D.C. 20549 \n\xa0 \xa0\nFORM 10-K  \xa0\n\xa0 \xa0\n\n\nþ\n ANNUAL REPORT PURSUANT TO SECTION\xa013 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934 \nFor the Fiscal Year Ended December\xa031, 2014 \n\xa0\n\n\n¨\n TRANSITION REPORT PURSUANT TO SECTION\xa013 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934 \nFor the Transition Period\nFrom\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0 to\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\n Commission file number 1-8400  \xa0\n\xa0 American\nAirlines Group Inc.  (Exact name of registrant as specified in its charter) \n\xa0 \xa0\n\xa0\n\n\n\n\n\n\nDelaware\n\xa0\n75-1825172\n\n (State or other jurisdiction of\nincorporation or organization)\n\xa0\n (I.R.S. Employer Identification No.)\n\n4333 Amon Carter Blvd., Fort Worth, Texas 76155\n\xa0\n(817) 963-1234\n\n(Address of principal executive offices, including zip code)\n\xa0\nRegistrant’s telephone number, including area code\n \xa0 (Former name, former address and\nformer fiscal year, if changed since last report)  Securities registered pursuant to Section\xa012(b) of the Act:\n \xa0\n\n\n\n\n\n\n\xa0\xa0\n\xa0\n Name of Exchange on Which Registered\n\nCommon Stock, $0.01 par value per share\n\xa0\nNASDAQ\n Securities registered pursuant to Section\xa012(g) of the Act: None \n\xa0 \xa0\nAmerican Airlines, Inc.  (Exact name of registrant as specified in its charter)  \xa0\n\xa0 \xa0\n\n\n\n\n\n\nDelaware\n\xa0\n13-1502798\n\n (State or other jurisdiction of\nincorporation or organization)\n\xa0\n (I.R.S. Employer Identification No.)\n\n4333 Amon Carter Blvd., Fort Worth, Texas 76155\n\xa0\n(817) 963-1234\n\n(Address of principal executive offices, including zip code)\n\xa0\nRegistrant’s telephone number, including area code\n Securities registered pursuant to Section\xa012(b) of the Act: None \nSecurities registered pursuant to Section\xa012(g) of the Act: None \n\xa0 \xa0\nIndicate by check mark if the registrant is a well-known seasoned issuer, as defined in Rule 405 of the Securities Act.\n \xa0\n\n\n\n\n\n\n\n\n American Airlines Group Inc.\n\xa0\xa0\n Yes\xa0þ\n\xa0\xa0\nNo\xa0¨\n\n American Airlines, Inc.\n\xa0\xa0\n Yes\xa0þ\n\xa0\xa0\nNo\xa0¨\n Indicate by check mark if the registrant is not required to file reports pursuant to\nSection\xa013 or Section\xa015(d) of the Act.  \xa0\n\n\n\n\n\n\n\n\n American Airlines Group Inc.\n\xa0\xa0\n Yes\xa0¨\n\xa0\xa0\nNo\xa0þ\n\n American Airlines, Inc.\n\xa0\xa0\n Yes\xa0¨\n\xa0\xa0\nNo\xa0þ\n Indicate by check mark whether the registrant (1)\xa0has filed all reports required to\nbe filed by Section\xa013 or 15(d) of the Securities Exchange Act of 1934 during the preceding 12 months (or for such shorter period that the registrant was required to file such reports), and (2)\xa0has been subject to such filing requirements\nfor the past 90 days.  \xa0\n\n\n\n\n\n\n\n\n American Airlines Group Inc.\n\xa0\xa0\n Yes\xa0þ\n\xa0\xa0\nNo\xa0¨\n\n American Airlines, Inc.\n\xa0\xa0\n Yes\xa0þ\n\xa0\xa0\nNo\xa0¨\n Indicate by check mark whether the registrant has submitted electronically and posted on\nits corporate Web site, if any, every Interactive Data File required to be submitted and posted pursuant to Rule 405 of Regulation S-T (§232.405 of this chapter) during the preceding 12 months (or for such shorter period that the registrant was\nrequired to submit and post such files).  \xa0\n\n\n\n\n\n\n\n\n American Airlines Group Inc.\n\xa0\xa0\n Yes\xa0þ\n\xa0\xa0\nNo\xa0¨\n\n American Airlines, Inc.\n\xa0\xa0\n Yes\xa0þ\n\xa0\xa0\nNo\xa0¨\n Indicate by check mark if disclosure of delinquent filers pursuant to Item\xa0405 of\nRegulation S-K (§ 229.405) is not cont'

We can clearly see that the document is divided based on the standard required elements. Business, Risk Factors, Unresolved Staff Comments, etc. are all standardized titles. This will help in our extrapolation step.

In [475]:
# Select Business as an example:
business = soup.find_all('a')[5]
print(business)

<a href="#i218984ca4fa54d3589b92be28c18f351_22" style="color:#0000ff;font-family:'Arial',sans-serif;font-size:10pt;font-weight:400;line-height:100%;text-decoration:underline">Risk Factors</a>

In [453]:
for filing_document in soup.find_all('DOCUMENT'):
  # The 'type' tag contains the document type
  document_type = filing_document.type.find(text=True, recursive=False).strip()

In [454]:
if document_type == "10-K":  # Once the 10K text body is found

  # Grab and store the 10K text body    
  TenKtext = filing_document.find('text').extract().text

In [455]:
document_type

'ZIP'

In [456]:
TenKtext

In [457]:
TenKtext = filing_document.find('text')
print(TenKtext)

<text>
begin 644 0000006201-21-000014-xbrl.zip
M4$L#!!0    ( #&gt;*45([W/G%]#@$  J#,P 6    83$P-#9A,S(P86=R965M
M96YT+FAT;&gt;R]&gt;7?;2+(G^O]\"DS5FQKI'$H6M7KIV^?0%&amp;6SKK9+4N6N]\\[
M()$4408!-A;)[$__(B(7)$ D1;EL*T&amp;C9ZY+$D@@$1D9&gt;_SB'__[_*8[^O.V
MY\S2&gt;&gt;#<wkv_>=7_9&gt;O?ITU'WUZGQT[GP&lt;75TZQ_L';6&lt;4NV'BIWX4NL&amp;K
M5[WK7YQ?9FFZ&gt;/OJU&gt;/CX_[CT7X4W[\:#5[AK8Y?!5&amp;4L'TO]7[YYS_P+_ O
M2SL[<g msn="">77T_]-_E/?YQRO^^S]&gt;T4/^,8Z\Y3__X?D/CN_]UR_^
M&amp;W8\/7"G\'^OSX[?O!Z_\5X?'+4/SZ:3DP-V=G;R_QV=P2I?P&gt;?YEY)T&amp;;#_
M^F7NAWLSA@MX&gt;W:X2-\]^EXZ&gt;]L^./@_O]#G_OF/:12F\+08OLQ_Y/=8N5/*
MOJ1[;N#?AV_IA7[A7Y67)U$0Q6]_/:#_OU-W[@?+M_]WY,]9XERS1V&lt;0
MS=WP_[82V(2]A,7^E'\P\?_#8$VP//KU4:P7[A/X(9/K;Q_BHGM?9O[83YWV
MP?[Q:7')^FN[\3V\&gt;1HMWK9?PWVUQ4^ UBR&amp;U:?N.R"^,H]EB\!V\1N(N$
MO94_O//\9!&amp;XR[=^2&amp;NA+[T3MQ]':1K-WY[  QY8G/H3-Q /H&gt;?QRSG)]P\X
MV5.@=&gt;K))XO+^W3I5&gt;JM7GOS&gt;O_-@?GRP7Y;77M%]^;WAU=(%F[X7[\<_5 m2="">R<n mtxro2f="">\&amp;CA].HWCNHLS "_@!..SP
MJ73F)XXG3F_+ 9[X#!?&amp;2V&lt;<ny m="" p="">&gt;.;L^+M.&amp;*7P?6!+?* ;&gt;O!'^.MCE 7X%7CL?,% .O@/+%C"3&gt;/Y-(.%
M39U%-@[\"?P-N'02@+#R]DNG6#'%*^+=:'0V#3%@G+YYY^'Z\Z.#+\-@D
MBFDSWV8A\"U^ZI=_=HX.#YR+SE7_\D^GTQ]T!YV+D;/)^[VIQ&gt;O=W@VZ'SO#
MGM/Y,.CUKGK7V_1R[WNC3[W&gt;]1:]$7#@^[NA,]SO[ _W:_9&gt;O_P31-Z0!0&amp;+
M:[;RM3MR?;Y-;W/5&amp;_2[G6L4=9?]Z]ZPY?2ON[7DM/?9LHK1-M%2XE:G1_"L
M1&lt;2=@K<q>ETD'_%'8/)DZ6K7WG"M.;_SF)YYX5[S_;&amp;X$M\
MWG.G0-2W;O#H+I-?OK\Y;RF;=IT;Y]H9.3WZ=_B\7?[&gt;+U-M0![\]FO[].#=
MZK_GO8O^=7_4O[D&gt;.OM6_L^T\A-+2-LV+7#8N03#!@2TM')^^_7DS3OGLH]/_I#ZQC72-4WEE#UQ$C5SI_D*HYZ@RN;M)9IO4&gt;V\.FI:857
MG&gt;N[BTYW=#?H.;&gt;#FV[O''_: ^L;)&gt;]W%KI&amp;LIU90K8STPJ[O?Z1964:9G';4L(^&lt;9LVU_V_^@-_K2,,_/_
M&amp;4E[9 EIVT:_J?&gt;O[MVP\QXL?*!RYT^R\T<w kz="" m_="">QWOS-Y
MC0ZZ+69/V^@ C0:=\QY0K#OHC5K.;6&gt;$9B42L7MS^^&gt;@_^'C"$R@\][5=7_T
M;8AH6LBI+;YBV^C+Y&amp;KYO#/J]
M 7B MX/&gt;$)@++,4_OC&gt;Y-J;?F35,9W1,X(#VK_O7'YSAW&gt;WMS6"D2[@?Z/H9
M*6@-!QI]E-[_W/5OR5U&amp;$E[V@1O!PSN_ZXX435^ A8-#VVAH=$#D<i3vb m_="">LZ!1G:![;PYJ'1"&gt;D,A_T/UWB@.6^"JKD&gt;7O0&amp;/SBB:":A+&gt;&amp;O0Z/G&lt;=4?
M=L' Z5SW;NZ&amp;J%9XG/O'QV3-1#2=;IN2LZ;5F_Y]JAQ"E *UDM&amp;GW/;UR?[QT=OOGLEJCV%HV?[)QOQ5N]?'_OO^Z-A
M1?7E3_'^H_[HLE?U]M6UIR\C &amp;3I&gt;&amp;?/J*V,6NRH_2:O#!V.0)-U!N BZ0GS
MFHHYJGW=VE=KU_S5+%E&gt;?G2,5LJ&amp;1Z=[[5SVAZ/^]0=+7JTVE#&gt;&amp;5SOE3@-];\-]8VQYK52IZ'^
MMZ#^^^&gt;["!<w><g:>"W
M7U\?ML_&gt;#9N-^58;TWW^X1 )VE*A+F[7W67'.3QHVU+E59LM&gt;/;9&gt;'(+5G.%
M/WFKE%T<:>M1;\!S@YU+3,'<wew2 mri="">X&lt;7K7'["E]&gt;D]LN3M&amp;U;Y*E9Y=F#@=M 9C9S??CUZ
M_=]'CW\-6]+L.0%:T+_WM?2_WW_\I(\V,YE
M0_)GD?SB^WG R8UX6L.*M7^*;FC02.J*QJ1 0CPZ^'S
MOOM;&amp;*KQ$)F2OPK=WNGX\22&amp;?71NLW@R<q gxi="" m="" m6a2-m_p="" nn-="">D74O!.R,L*_OB)RFB/!-,F7,1
MLW R<p i8rsejgqv="" m="">\#]SYT)WM=YK$O+;B]&amp;^*WXQ,8D[,R7-3"!".UWNRUKQ&amp;OU.O%<v mhqlckg2="">#A%[<p mjr_="">4+:&lt;0*JU&gt;&gt;F S 9X;(K^[9%
MGQ6(Q!Y+_!A6!'=(X"]T2=G&amp;XK8&lt;4C:*Z9=+EB11W**GY!&gt;UVRRD00U?"!C^
M4+CG-([F^@)*MX6;+."-"-?==A:XOOGDC) -+FX&amp;/:<_ m="">7GS:?C;KR&gt;OWYE?1#0V\1D#1Z&gt;RM<d>XRUO3L8?S20;
M &gt;!NPN?'V'CV0H8%Z#/'!&gt;D 9QLXA54(%6?'8U.: S%F0?0(IA+[,F&amp;+U '=
M%\$!CQ]]D 3LRP(.&gt; )N]2*.'GR/&gt;5P832,P^Q]1VW(1]NC#PT#_LM+5.7-#
M^&amp;_RQ*&amp;RP!A;/UL!^W^$0'Q1_2$3;&amp;ZX=,06T\Z"O(8U[L%)=.:1QP+'E&gt;(;
MI --]- D.&amp;H"*?35-:4S*KX@U H7^?1UTA-&gt;4=_ +9/,#846*BHPL,:"S"-^
M$6M%&gt;DYC=\Z=0WP1'!$2A?#Q!'CQWYF_X%\%KSKE.M*=3&amp;@%/A#4#Q/PY@(^
MQ@06!59=DH$CJ]Y;JCMW 7[XA%J;Z;&amp;W$2_-&amp;Y=BMD&gt;P87,E@'
MFI@@B6.+E-K7LBV1V1JV+1PFDCIESEC=(MJ8:137?"^HL:&amp;&gt;8@0.L/2TQ%;A
M6GHAT)PY-POROYXG:IXI+@3M7D)DX*-_-K&amp;AD]L:5ETY1)7BHWJ[MDB$?(BC
M;.&amp;TZR!*"KL%=F'L/,[\R4P3 SA?#!Q9QP
M_VB[=M/2TU;FMY_YU!W6[]21-P?7W+#X@?*V;M&lt;&gt;67V6#G_RL[3R<g9l5. a8b="" m="" mf="" mn="">/2@)8P2=JDQ*YQJ2P27)4L"Q%^!W!_?8/
MVO!OR^GC3CMG+&lt;&gt;C8I/?LY"I8JR6L/NY8P\K=YVY^\6?9Z#6W,]L+YI.';Y$
M9^=J=/-I%\V9]NEIZ_CXC;.(@(1)2_M. *M#C:F^<bf .i="" m_v="">G!UH3YI$BR5&gt;$<o>X7L"[P6*F%P08!=-2RV
M.G,D BS9;M(&gt;'NP=UB6TS&gt;GYP^-4\-B?*D:ED=D:MBT<ie7 m="">O%RN5K6'+B@!!SJ2ZT"J*%XX MP7!@7QKWF-URRT\(?+LV)TJ%^@(
M'*!VO9V@G.(U27F5L@KJ4!0":86#H5_9GJVJT0&amp;I=5"FQ%IVT'ICP_MED\$Y
M[5["R/[IDL$E<eo>"?Y]35
M(!E,W(?UISG!\])!A^?M$X.
M3IZ?#"XDD9^=#*ZWP*J#(]FN43*X_3)QJO9/%J.RTV-&gt;ZR57;=%66/7MFH2V
M*\7("X&gt;VVR\7VFY_L]!V4[=0I[J%MK7A_?93X7T3RVZ1&amp;*U/&gt;+_=A/&gt;?LYN6
MGK8-POL_S:FK0WB__51XOWI;MVN/K#Y+:\/[/\%9JEF\^;3F)*\9N&gt;NNU&gt;T+
MVZZ&amp;]]LO%-XW/O=G"&gt;^;"&amp; %GZA-VC"\WUL-[Y]\N_#^X#&gt;%QE?C7N/6!^T@ &gt;1)4MK4&gt;"CN()AQ-.W7:;UX[?X"M_3Z+&amp;&gt;C;-&amp;8,
MK+QAYJ?,.%+&gt;</eo></ie7></o></bf></g9l5.></d></_></p></v></p></q></wew2></:></g:></w></i3vb></w></q></ny></n></_5></g></wkv_></text>

In [247]:
print(business.get_text())

Business

In [262]:
first_par = soup.findAll('p')[100]
text_between = first_par.next_sibling

In [263]:
print(text_between)

In [250]:
container = soup.find('div', class_='td-post-content')
for para in container.find_all('p', recursive=False):
    print(para.text)

AttributeError: 'NoneType' object has no attribute 'find_all'

In [213]:
#for i in soup.prettify().split('<!--Persontype-->')[1].split('<a>'):
#    print('<strong>' + ''.join(i))

In [509]:
#for i in soup.prettify().split('</a>')[1:2]:
#    print(''.join(i))

In [215]:
#print(asdf[1])

## Attempting Other Code

https://gist.github.com/anshoomehra/ead8925ea291e233a5aa2dcaa2dc61b2

In [216]:
raw_10k[:1000]

'<html><body><document>\n<type>10-K\n<sequence>1\n<filename>d286458d10k.htm\n<description>FORM 10-K\n<text>\n<title>Form 10-K</title>\n<h5 align="left"><a href="#toc">Table of Contents</a></h5>\n<p style="line-height:2px;margin-top:0px;margin-bottom:0px;border-bottom:2pt solid #435363">&#160;</p>\n<p style="line-height:3px;margin-top:0px;margin-bottom:2px;border-bottom:0.5pt solid #435363">&#160;</p> <p align="center" style="margin-top:1px;margin-bottom:0px"><font color="#435363" size="2" style="font-family:ARIAL"><b>UNITED STATES SECURITIES\nAND EXCHANGE COMMISSION </b></font></p> <p align="center" style="margin-top:0px;margin-bottom:0px"><font color="#435363" size="2" style="font-family:ARIAL"><b>Washington, D.C. 20549 </b></font></p>\n<p style="font-size:1px;margin-top:0px;margin-bottom:0px">&#160;</p><center> <p style="line-height:6px;margin-top:0px;margin-bottom:2px;border-bottom:1pt solid #435363;width:21%">&#160;</p></center>\n<p align="center" style="margin-top:1px;margin-bottom:0px"><font '

In [498]:
# Regex to find <DOCUMENT> tags
doc_start_pattern = re.compile(r'<document>')
doc_end_pattern = re.compile(r'</document>')
# Regex to find <TYPE> tag prceeding any characters, terminating at new line
type_pattern = re.compile(r'<type>[^\n]+')

In [499]:
# Create 3 lists with the span idices for each regex

### There are many <Document> Tags in this text file, each as specific exhibit like 10-K, EX-10.17 etc
### First filter will give us document tag start <end> and document tag end's <start> 
### We will use this to later grab content in between these tags
doc_start_is = [x.end() for x in doc_start_pattern.finditer(raw_10k)]
doc_end_is = [x.start() for x in doc_end_pattern.finditer(raw_10k)]

### Type filter is interesting, it looks for <TYPE> with Not flag as new line, ie terminare there, with + sign
### to look for any char afterwards until new line \n. This will give us <TYPE> followed Section Name like '10-K'
### Once we have have this, it returns String Array, below line will with find content after <TYPE> ie, '10-K' 
### as section names
doc_types = [x[len('<type>'):] for x in type_pattern.findall(raw_10k)]

In [516]:
doc_types

['10-K']

In [517]:
document = {}

# Create a loop to go through each section type and save only the 10-K section in the dictionary
for doc_type, doc_start, doc_end in zip(doc_types, doc_start_is, doc_end_is):
    if doc_type == '10-K':
        document[doc_type] = raw_10k[doc_start:doc_end]

In [518]:
# display excerpt the document
document['10-K'][0:500]

'\n<type>10-K\n<sequence>1\n<filename>d829913d10k.htm\n<description>FORM 10-K\n<text>\n<title>Form 10-K</title>\n<h5 align="left"><a href="#toc">Table of Contents</a></h5>\n<p style="line-height:4px;margin-top:0px;margin-bottom:0px;border-bottom:2pt solid #000000">&#160;</p>\n<p style="line-height:3px;margin-top:0px;margin-bottom:2px;border-bottom:0.5pt solid #000000">&#160;</p> <p align="center" style="margin-top:1px;margin-bottom:0px"><font size="2" style="font-family:Times New Roman"><b>UNITED STATES S'

In [519]:
# Write the regex
regex = re.compile(r'(>Item(\s|&#160;|&nbsp;)(1A|1B|7A|7|8)\.{0,1})|(ITEM\s(1A|1B|7A|7|8))')

# Use finditer to math the regex
matches = regex.finditer(document['10-K'])

# Write a for loop to print the matches
for match in matches:
    print(match)

<re.Match object; span=(31194, 31208), match='>Item&#160;1A.'>
<re.Match object; span=(31937, 31951), match='>Item&#160;1B.'>
<re.Match object; span=(37030, 37043), match='>Item&#160;7.'>
<re.Match object; span=(37875, 37889), match='>Item&#160;7A.'>
<re.Match object; span=(38666, 38678), match='>Item&#160;8'>
<re.Match object; span=(39487, 39499), match='>Item&#160;8'>

In [520]:
# Matches
matches = regex.finditer(document['10-K'])

# Create the dataframe
test_df = pd.DataFrame([(x.group(), x.start(), x.end()) for x in matches])

test_df.columns = ['item', 'start', 'end']
test_df['item'] = test_df.item.str.lower()

# Display the dataframe
test_df.head()

             item  start    end
0  >item&#160;1a.  31194  31208
1  >item&#160;1b.  31937  31951
2   >item&#160;7.  37030  37043
3  >item&#160;7a.  37875  37889
4    >item&#160;8  38666  38678

In [521]:
# Get rid of unnesesary charcters from the dataframe
test_df.replace('&#160;',' ',regex=True,inplace=True)
test_df.replace('&nbsp;',' ',regex=True,inplace=True)
test_df.replace(' ','',regex=True,inplace=True)
test_df.replace('\.','',regex=True,inplace=True)
test_df.replace('>','',regex=True,inplace=True)

# display the dataframe
test_df.head()

     item  start    end
0  item1a  31194  31208
1  item1b  31937  31951
2   item7  37030  37043
3  item7a  37875  37889
4   item8  38666  38678

In [522]:
# Drop duplicates
pos_dat = test_df.sort_values('start', ascending=True).drop_duplicates(subset=['item'], keep='last')

# Display the dataframe
pos_dat

     item  start    end
0  item1a  31194  31208
1  item1b  31937  31951
2   item7  37030  37043
3  item7a  37875  37889
5   item8  39487  39499

In [523]:
# Set item as the dataframe index
pos_dat.set_index('item', inplace=True)

# display the dataframe
pos_dat

        start    end
item
item1a  31194  31208
item1b  31937  31951
item7   37030  37043
item7a  37875  37889
item8   39487  39499

In [525]:
# Get Item 1a
item_1a_raw = document['10-K'][pos_dat['start'].loc['item1a']:pos_dat['start'].loc['item1b']]

# Get Item 7
item_7_raw = document['10-K'][pos_dat['start'].loc['item7']:pos_dat['start'].loc['item7a']]

# Get Item 7a
item_7a_raw = document['10-K'][pos_dat['start'].loc['item7a']:pos_dat['start'].loc['item8']]

In [528]:
document['10-K'][:500]

'\n<type>10-K\n<sequence>1\n<filename>d829913d10k.htm\n<description>FORM 10-K\n<text>\n<title>Form 10-K</title>\n<h5 align="left"><a href="#toc">Table of Contents</a></h5>\n<p style="line-height:4px;margin-top:0px;margin-bottom:0px;border-bottom:2pt solid #000000">&#160;</p>\n<p style="line-height:3px;margin-top:0px;margin-bottom:2px;border-bottom:0.5pt solid #000000">&#160;</p> <p align="center" style="margin-top:1px;margin-bottom:0px"><font size="2" style="font-family:Times New Roman"><b>UNITED STATES S'

In [529]:
### First convert the raw text we have to exrtacted to BeautifulSoup object 
item_1a_content = BeautifulSoup(item_1a_raw, 'lxml')

In [530]:
### By just applying .pretiffy() we see that raw text start to look oragnized, as BeautifulSoup
### apply indentation according to the HTML Tag tree structure
print(item_1a_content.prettify()[0:1000])

<html>
 <body>
  <p>
   &gt;Item 1A.
  </p>
  <td valign="bottom">
   <font size="1">
   </font>
  </td>
  <td valign="top">
   <font size="2" style="font-family:Times New Roman">
    <a href="#tx829913_3">
     Risk Factors
    </a>
   </font>
  </td>
  <td valign="bottom">
   <font size="1">
   </font>
  </td>
  <td nowrap="" valign="bottom">
   <font size="2" style="font-family:Times New Roman">
   </font>
  </td>
  <td align="right" nowrap="" valign="bottom">
   <font size="2" style="font-family:Times New Roman">
    30
   </font>
  </td>
  <td nowrap="" valign="bottom">
   <font size="2" style="font-family:Times New Roman">
   </font>
  </td>
  <tr>
   <td nowrap="" valign="top">
    <p style="margin-left:4.50em; text-indent:-4.50em">
     <font size="2" style="font-family:Times New Roman">
     </font>
    </p>
   </td>
  </tr>
 </body>
</html>

In [531]:
### Our goal is though to remove html tags and see the content
### Method get_text() is what we need, \n\n is optional, I just added this to read text 
### more cleanly, it's basically new line character between sections. 
print(item_1a_content.get_text())

>Item 1A.

Risk Factors


30

In [203]:
item_1a_raw

'>Item&#160;1A.&#160;&#160;&#160;&#160;</font></p></td>\n<td valign="bottom"><font size="1">&#160;</font></td>\n<td valign="top"><font color="#435363" size="2" style="font-family:ARIAL"><a href="#tx286458_3">Risk Factors</a></font></td>\n<td valign="bottom"><font size="1">&#160;&#160;</font></td>\n<td nowrap="" valign="bottom"><font color="#435363" size="2" style="font-family:ARIAL">&#160;</font></td>\n<td align="right" nowrap="" valign="bottom"><font color="#435363" size="2" style="font-family:ARIAL">16</font></td>\n<td nowrap="" valign="bottom"><font color="#435363" size="2" style="font-family:ARIAL">&#160;</font></td></tr>\n<tr style="page-break-inside:avoid">\n<td nowrap="" valign="top"> <p style="margin-left:4.50em; text-indent:-4.50em"><font color="#435363" size="2" style="font-family:ARIAL"'

In [199]:
document["10-K"][:500]

'\n<type>10-K\n<sequence>1\n<filename>d286458d10k.htm\n<description>FORM 10-K\n<text>\n<title>Form 10-K</title>\n<h5 align="left"><a href="#toc">Table of Contents</a></h5>\n<p style="line-height:2px;margin-top:0px;margin-bottom:0px;border-bottom:2pt solid #435363">&#160;</p>\n<p style="line-height:3px;margin-top:0px;margin-bottom:2px;border-bottom:0.5pt solid #435363">&#160;</p> <p align="center" style="margin-top:1px;margin-bottom:0px"><font color="#435363" size="2" style="font-family:ARIAL"><b>UNITED ST'